name: taxi_driver
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  # BASE
  cupertino_icons: ^1.0.5
  intl: ^0.18.1
  google_fonts: ^5.1.0
  html: ^0.15.4
  shared_preferences: ^2.2.0
  flutter_widget_from_html: ^0.10.3

  # TOAST
  fluttertoast: ^8.2.2

  # IMAGE
  cached_network_image: ^3.2.3

  # UI
  sliding_up_panel: ^2.0.0+1
  dotted_line: ^3.2.2
  lottie: ^2.5.0
  flutter_rating_bar: ^4.0.1
  flutter_staggered_animations: ^1.1.1
  bottom_picker: ^2.0.4
  country_code_picker: ^3.0.0
  flutter_native_contact_picker: ^0.0.4
  timeline_tile: ^2.0.0
  flutter_vector_icons: ^2.0.0
  flutter_switch: ^0.3.2
  syncfusion_flutter_charts: ^22.1.39

  #OTP TEXT FIELD
  otp_text_field: ^1.1.3

  #MAP
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  google_maps_flutter: ^2.3.1
  flutter_polyline_points: ^1.0.0
  location: ^4.4.0

  #IMAGES
  image_picker: ^1.0.1
  file_picker: ^5.3.2
  date_time_picker: ^2.1.0

  #CONNECTIVITY
  package_info_plus: ^4.0.2
  http: ^1.1.0
  connectivity_plus: ^4.0.1
  url_launcher: ^6.1.12

  #FIREBASE
  firebase_crashlytics: ^3.3.4
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0
  firebase_storage: ^11.2.5
  firebase_database: ^10.2.4
  paginate_firestore: ^1.0.3+1
  cloud_firestore: ^4.8.3

  #STATE MANAGEMENT
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5

  #PAYMENT GATEWAY
  razorpay_flutter: ^1.3.5
  flutter_stripe: ^9.2.2
  flutter_paystack: ^1.0.7
  flutter_braintree: ^3.0.0
  flutterwave_standard: ^1.0.8
  flutter_paytabs_bridge: ^2.4.4
  mercado_pago_mobile_checkout: ^0.2.0-dev.3
  my_fatoorah: ^3.3.0
  paytm: ^3.0.1


  # PUSH NOTIFICATION
  onesignal_flutter: ^3.5.1

  #SOCIAL LOGIN
  google_sign_in: ^6.1.4
  the_apple_sign_in: ^1.1.1

  #MQTT
  mqtt_client: ^10.0.0

  #DOWNLOAD INVOICE PDF
  pdf: ^3.10.4
  path_provider: ^2.0.15
  open_file: ^3.3.2
  printing: ^5.11.0
  flutter_ringtone_player: ^3.2.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0
  change_app_package_name: ^1.1.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  intl: ^0.18.0
  cloud_firestore: ^4.8.1
  http: ^1.0.0
  chewie: ^1.5.0


flutter:

  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - images/flag/
    - images/ringtone.mp3
